// <auto-generated />
using System;
using CodeCollab.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeCollab.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323125049_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CodeCollab.API.Models.AiLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("call_type");

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("called_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("ai_logs");
                });

            modelBuilder.Entity("CodeCollab.API.Models.CodeSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("saved_at");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("code_snapshots");
                });

            modelBuilder.Entity("CodeCollab.API.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_active_at");

                    b.HasKey("Id");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("CodeCollab.API.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("CodeCollab.API.Models.AiLog", b =>
                {
                    b.HasOne("CodeCollab.API.Models.Room", "Room")
                        .WithMany("AiLogs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CodeCollab.API.Models.CodeSnapshot", b =>
                {
                    b.HasOne("CodeCollab.API.Models.Room", "Room")
                        .WithMany("CodeSnapshots")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CodeCollab.API.Models.Session", b =>
                {
                    b.HasOne("CodeCollab.API.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CodeCollab.API.Models.Room", b =>
                {
                    b.Navigation("AiLogs");

                    b.Navigation("CodeSnapshots");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
